#ifndef __DEFINES__
#define __DEFINES__

#define BACK_DOOR_OPEN_ANGLE 180
#define DOOR_CLOSED_ANGLE 90
#define FRONT_DOOR_OPEN_ANGLE 0
#define SWEEP_TIME 200 //Optimal for the SG90. 180 could is the minimum acceptable.

#define TEMPERATURE_THRESHOLD 25
#define MAX_WASTE_LEVEL 0.5f
#define MIN_WASTE_LEVEL 0.05f

#define SCHEDULE_PERIOD 50
#define MEASURE_LEVEL_PERIOD 50
#define MEASURE_TEMPERATURE_PERIOD 300
#define WASTE_DISPOSAL_TASK_PERIOD 100

#define ENTERING_WASTE_PERIOD 5000
#define WASTE_RECEIVED_PERIOD 2000
#define AWAKE_PERIOD 10000
#define EMPTYING_PROCESS 2000

#endif
