#ifndef __DEFINES__
#define __DEFINES__

#define BACK_DOOR_OPEN_ANGLE 0
#define DOOR_CLOSED_ANGLE 90
#define FRONT_DOOR_OPEN_ANGLE 180
#define SWEEP_TIME 150

#define TEMPERATURE_THRESHOLD 25
#define MAX_WASTE_LEVEL 20
#define MIN_WASTE_LEVEL 5

#define SCHEDULE_PERIOD 50
#define MEASURE_LEVEL_PERIOD 50
#define MEASURE_TEMPERATURE_PERIOD 300
#define WASTE_DISPOSAL_TASK_PERIOD 200

#define GREEN_LED_PIN 3
#define RED_LED_PIN 4

#endif
