#ifndef __DEFINES__
#define __DEFINES__

#define TEMPERATURE_THRESHOLD 25
#define MAX_WASTE_LEVEL 20
#define MIN_WASTE_LEVEL 5

#define SCHEDULE_PERIOD 50
#define MEASURE_LEVEL_PERIOD 50
#define MEASURE_TEMPERATURE_PERIOD 300
#define WASTE_DISPOSAL_TASK_PERIOD 200

#endif
